version: 1

phases:
  install:
    runtime-versions:
      nodejs: 18.12.0
  build:
    commands:
      - npm install
  post_build:
    commands:
      - npm run build # You can add any additional build steps here, like TypeScript compilation or database migrations

artifacts:
  files:
    - '**/*' # Include all files in the build artifact

cache:
  paths:
    - node_modules/ # Cache the node_modules directory to speed up future builds
